---
abstract: ~
author:
  - 'Fabien Wernli <wernli at in2p3.fr>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Pod::Markdown: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.15'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Golger
no_index:
  directory:
    - inc
recommends:
  Config::Any: 0
requires:
  AnyEvent::WebSocket::Client: 0
  Getopt::Long::Descriptive: 0
  JSON::Any: 0
  URI::Escape: 0
  perl: 5.8.2
resources:
  license: http://dev.perl.org/licenses/
version: '0.1'
